version: "3.8"

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clinic_hms
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/clinic_hms?schema=public
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: change-this-secret-in-production
    depends_on:
      - db

volumes:
  pgdata:
